/*Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.


This is not that hard.  

We can i 
 * */


package main

import "math"

func isPentagonal(x int) bool {
    return  math.Mod((math.Sqrt(24*float64(x) + 1) + 1),6) == 0
}

// returns the nth hexagonal number
func hexagonal(n int) int {
    return n*(2*n - 1)
}


func main(){
    n := 144 // this starts after the point euler gave us.
    done := false
    ans := -5
    for !done{
        ans = hexagonal(n)
        if isPentagonal(ans) { 
            done = true
        } else {
            n++
        }
        
    }
    println(n,ans)
}
